---
spring:
 application:
  name: "hr"
 profiles:
  active: "smart"
 
salary:
  defaultPercent: 5
  smart:
    limits:
    - year: 10
      percent: 10
    - year: 5
      percent: 5
    - year: 2.5
      percent: 2